/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Skripsi_IlhamLazuardi;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author Lazuardi
 */
public class FormSetrika extends javax.swing.JFrame {
    Connection koneksi;
    ResultSet hasil;
    PreparedStatement proses;
    Statement stmn;

    /**
     * Creates new form FormSetrika
     */
    public FormSetrika() {
        initComponents();
        auto_number();
        txtNama.requestFocus();
        Date start = new Date();
        txtTanggal.setDate(start);
    }
    
    private void auto_number(){
    try{
        String sql = "SELECT MAX(right(Kodebon,2)) AS no FROM dbsetrika";
        koneksi = Skripsi_IlhamLazuardi.KoneksiDB.ConnectDb();
            proses = koneksi.prepareStatement(sql);
            hasil = proses.executeQuery(sql);
            while(hasil.next()){
                if(hasil.first() == false){
                    txtKodeBon.setText("ST001");
                    
                }else {
                    hasil.last();
                    int auto_id = hasil.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int noLong  = no.length();
                                  for(int a  = 0; a<3-noLong; a++){
                                      no = "0" + no;
                                  }
                                  txtKodeBon.setText("ST" + no);
                }
                
            }
    } catch (Exception e) {
        JOptionPane.showInternalMessageDialog(this, "Error: \n" + e.toString(),"ADA KESALAHAN!",JOptionPane.WARNING_MESSAGE);
    }
}

    
    
public final void search_data(){
    DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Kodebon");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        model.addColumn("Tanggal");
        
        model.addColumn("Jenis Barang");
        model.addColumn("Harga");
        model.addColumn("Total Harga");
        model.addColumn("Banyak Barang");
        
        String no = txtCari.getText();
    
    try{
            String sql = "SELECT * FROM `dbsetrika` WHERE `Kodebon` LIKE '%"+no+"%'";
            koneksi = Skripsi_IlhamLazuardi.KoneksiDB.ConnectDb();
            proses = koneksi.prepareStatement(sql);
            hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6),hasil.getString(7),hasil.getString(8),hasil.getString(9),hasil.getString(10)});
                
                }
            tabelSetrika.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }



public final void tglskrng(){
    Date sekarang = new Date();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String tanggal = dateFormat.format(txtTanggal.getDate());
}

private void kosong(){
    txtKodeBon.setText("");
    txtNama.setText("");
    txtAlamat.setText("");
    txtTelepon.setText("");
    txtHarga.setText("");
    txtBanyakBarang.setText("");
    txtTotalHarga.setText("");
    txtJenis.setSelectedIndex(0);
    txtCari.setText("");
    txtSemuaTotal.setText("");
    txtNama.requestFocus();
    auto_number();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKodeBon = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtTelepon = new javax.swing.JTextField();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtJenis = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        txtBanyakBarang = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        BtnAdd = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelSetrika = new javax.swing.JTable();
        btnTotal = new javax.swing.JButton();
        txtSemuaTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtUang = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BtnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SETRIKA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lazuardi\\Documents\\NetBeansProjects\\Skripsi_IlhamLazuardi\\Icon\\LOGO BJ 100x100.png")); // NOI18N
        jLabel9.setText("SETRIKA");

        jLabel1.setText("Kode Bon");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        txtTanggal.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("Telp");

        jLabel5.setText("Tanggal");

        jLabel6.setText("Berat");

        jLabel7.setText("Harga");

        jLabel8.setText("Banyak Barang");

        jLabel10.setText("Total Harga");

        jLabel11.setText("Cari");

        txtJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Kg", "2 Kg", "3 Kg", "4 Kg", "5 Kg", "6 Kg", "7 Kg", "8 Kg", "9 Kg", "10 Kg", "11 Kg", "12 Kg", "13 Kg", "14 Kg", "15 Kg", "16 Kg", "17 Kg", "18 Kg", "19 Kg", "20 Kg" }));
        txtJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisActionPerformed(evt);
            }
        });

        txtBanyakBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBanyakBarangKeyReleased(evt);
            }
        });

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        BtnAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lazuardi\\Documents\\NetBeansProjects\\Skripsi_IlhamLazuardi\\Icon\\Icon tambah 20x20.png")); // NOI18N
        BtnAdd.setText("Tambah");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        btnCari.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lazuardi\\Documents\\NetBeansProjects\\Skripsi_IlhamLazuardi\\Icon\\Icon cari 20x20.png")); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnTambah.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lazuardi\\Documents\\NetBeansProjects\\Skripsi_IlhamLazuardi\\Icon\\Icon tambah 20x20.png")); // NOI18N
        btnTambah.setText("Simpan Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lazuardi\\Documents\\NetBeansProjects\\Skripsi_IlhamLazuardi\\Icon\\Icon hapus 20x20.png")); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lazuardi\\Documents\\NetBeansProjects\\Skripsi_IlhamLazuardi\\Icon\\Icon update 20x20.png")); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lazuardi\\Documents\\NetBeansProjects\\Skripsi_IlhamLazuardi\\Icon\\icon reset 20x20.png")); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        Kembali.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lazuardi\\Documents\\NetBeansProjects\\Skripsi_IlhamLazuardi\\Icon\\Icon kembali ke menu 20x20.png")); // NOI18N
        Kembali.setText("Kembali Ke Menu");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tabelSetrika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KodeBon", "Nama", "Telepon", "Alamat", "Tanggal", "Jenis Barang", "Harga", "Total Harga", "Banyak Barang"
            }
        ));
        tabelSetrika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSetrikaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelSetrika);

        btnTotal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lazuardi\\Documents\\NetBeansProjects\\Skripsi_IlhamLazuardi\\Icon\\icon keuntungan 20x20.png")); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        jLabel12.setText("Uang");

        txtUang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUangKeyReleased(evt);
            }
        });

        jLabel13.setText("Kembalian");

        BtnPrint.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lazuardi\\Documents\\NetBeansProjects\\Skripsi_IlhamLazuardi\\Icon\\icon print 20x20.png")); // NOI18N
        BtnPrint.setText("Cetak Struk");
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(txtKodeBon)
                            .addComponent(jScrollPane1)
                            .addComponent(txtTelepon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtJenis, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBanyakBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtHarga)
                            .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnAdd)
                            .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kembali)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSemuaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtUang)))
                            .addComponent(BtnPrint))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtKodeBon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtBanyakBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnAdd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCari))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnUpdate)
                    .addComponent(btnReset)
                    .addComponent(Kembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtSemuaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPrint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        if (txtCari.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "SILAHKAN MASUKKAN KODE BON!");
        }else{
       Connection connj = null;
        Statement stmtj = null;
            
            String no = txtCari.getText();
            try
            {
              
                connj = Skripsi_IlhamLazuardi.KoneksiDB.ConnectDb();
                stmtj = connj.createStatement();
                String query = "select*from dbsetrika where Kodebon like'%"+no+"%'";
            
            ResultSet hasil = stmtj.executeQuery(query);
                
                while (hasil.next())
                {
                    //txt berarti dari field ,getstring(ngambil dari database coloumn ) 
                    txtKodeBon.setText(hasil.getString("kodebon"));
                    txtNama.setText(hasil.getString("nama"));
                    txtAlamat.setText(hasil.getString("alamat"));
                    txtTelepon.setText(hasil.getString("telepon"));
                    txtJenis.setSelectedItem(hasil.getString("JenisBarang"));
                    txtHarga.setText(hasil.getString("HargaKiloan"));
                    txtBanyakBarang.setText(hasil.getString("BanyakBarang"));
                    
                    
                }
                
            }catch(SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        search_data();
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        kosong();
        Date start = new Date();
        txtCari.setText("");
        txtTanggal.setDate(start);
        auto_number();
        for (int i = 0; i < tabelSetrika.getRowCount(); i++)
        for(int j = 0; j < tabelSetrika.getColumnCount(); j++) {
        tabelSetrika.setValueAt("", i, j);
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FormUtama().setVisible(true);
                dispose();
            }
        });
    }//GEN-LAST:event_KembaliActionPerformed

    private void txtJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisActionPerformed
        // TODO add your handling code here:
        int harga = 0;
         int total = 0;
        if(txtJenis.getSelectedItem() == "1 Kg"){
            harga = 7000;
            total = 7000;
        }
        else if(txtJenis.getSelectedItem() == "2 Kg"){
          harga = 14000;
          total = 14000;
        }
        else if(txtJenis.getSelectedItem() == "3 Kg"){
          harga = 21000;
          total = 21000;
        }
        else if(txtJenis.getSelectedItem() == "4 Kg"){
          harga = 28000;
          total = 28000;
          
        }
        else if(txtJenis.getSelectedItem() == "5 Kg"){
          harga = 35000;
          total = 35000;
          
        }
        else if(txtJenis.getSelectedItem() == "6 Kg"){
          harga = 42000;
          total = 42000;
        }
        else if(txtJenis.getSelectedItem() == "7 Kg"){
          harga = 49000;
          total = 49000;
          
        }
        else if(txtJenis.getSelectedItem() == "8 Kg"){
          harga = 56000;
          total = 56000;
          
        }
        else if(txtJenis.getSelectedItem() == "9 Kg"){
          harga = 63000;
          total = 63000;
          
        }
        
        else if(txtJenis.getSelectedItem() == "10 Kg"){
          harga = 70000;
          total = 70000;
          
        }
        else if(txtJenis.getSelectedItem() == "11 Kg"){
          harga = 77000;
          total = 77000;
          
        }
        else if(txtJenis.getSelectedItem() == "12 Kg"){
          harga = 84000;
          total = 84000;
          
        }
        else if(txtJenis.getSelectedItem() == "13 Kg"){
          harga = 91000;
          total = 91000;
          
        }
        else if(txtJenis.getSelectedItem() == "14 Kg"){
          harga = 98000;
          total = 98000;
          
        }
        else if(txtJenis.getSelectedItem() == "15 Kg"){
          harga = 105000;
          total = 105000;
          
        }
        else if(txtJenis.getSelectedItem() == "16 Kg"){
          harga = 112000;
          total = 112000;
          
        }
        else if(txtJenis.getSelectedItem() == "17 Kg"){
          harga = 119000;
          total = 119000;
          
        }
        else if(txtJenis.getSelectedItem() == "18 Kg"){
          harga = 126000;
          total = 126000;
          
        }
        else if(txtJenis.getSelectedItem() == "19 Kg"){
          harga = 133000;
          total = 133000;
          
        }
        else if(txtJenis.getSelectedItem() == "20 Kg"){
          harga = 140000;
          total = 140000;
          
        }
        
        else{
            harga = 0;
        }
        txtHarga.setText(String.valueOf(+harga));
        txtTotalHarga.setText(String.valueOf(+total));
    }//GEN-LAST:event_txtJenisActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        Connection koneksi = null;
        Statement stmt = null;
        try {
            
        koneksi = Skripsi_IlhamLazuardi.KoneksiDB.ConnectDb();
        stmt = koneksi.createStatement();
        
       for(int i = 0 ; i <  tabelSetrika.getRowCount(); i++){
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String Tanggal = dateFormat.format(txtTanggal.getDate());
                    String Ilham = ("'"+(String)tabelSetrika.getModel().getValueAt(i,0)+"'"+", ")+("'"+(String)tabelSetrika.getModel().getValueAt(i,1)+"'"+", ")+("'"+(String)tabelSetrika.getModel().getValueAt(i,2)+"'"+", ")+("'"+(String)tabelSetrika.getModel().getValueAt(i,3)+"'"+", ")+("'"+(String)tabelSetrika.getModel().getValueAt(i,4)+"'"+", ")+("'"+(String)tabelSetrika.getModel().getValueAt(i,5)+"'"+", ")+("'"+(String)tabelSetrika.getModel().getValueAt(i,6)+"'"+", ")+("'"+(String)tabelSetrika.getModel().getValueAt(i,7)+"'"+", ")+("'"+(String)tabelSetrika.getModel().getValueAt(i,8)+"'");

                stmt.executeUpdate("INSERT INTO `dbsetrika`(`Kodebon`,`Nama`, `Alamat`,`Telepon`,`Tanggal`,`JenisBarang`,`HargaKiloan`, `TotalHarga`,`BanyakBarang`) VALUES  ("+Ilham+")");
//                System.out.println(fa);
//            }
        }
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        } catch(SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String Tanggal = dateFormat.format(txtTanggal.getDate());
        int i = tabelSetrika.getSelectedRow();
        DefaultTableModel Model = (DefaultTableModel)tabelSetrika.getModel();
        if (i >= 0)
        {
            Model.setValueAt(txtKodeBon.getText(), i ,0);
            Model.setValueAt(txtNama.getText(), i ,1);
            Model.setValueAt(txtTelepon.getText(), i ,3);
            Model.setValueAt(txtAlamat.getText(), i ,2);
            Model.setValueAt(Tanggal, i, 4);
            Model.setValueAt(txtJenis.getSelectedItem(), i ,5);
            Model.setValueAt(txtHarga.getText(), i ,6);
            Model.setValueAt(txtTotalHarga.getText(),i , 7);
            Model.setValueAt(txtBanyakBarang.getText(), i ,8);
        }
        else {
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tabelSetrika.getModel();
        if(tabelSetrika.getSelectedRow() == -1 ){
            if(tabelSetrika.getRowCount() == 0 ){
                IMessage.setText("Tabel masih kosong");
            } else {
                IMessage.setText("Kamu Harus Select Kolomnya");
            }
        } else {
            model.removeRow(tabelSetrika.getSelectedRow());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
        if (txtCari.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "SILAHKAN MASUKKAN KODE BON!");
        }else{
       Connection connj = null;
        Statement stmtj = null;
            
            String no = txtCari.getText();
            try
            {
              
                connj = Skripsi_IlhamLazuardi.KoneksiDB.ConnectDb();
                stmtj = connj.createStatement();
                String query = "select*from dbsetrika where Kodebon like'%"+no+"%'";
            
            ResultSet hasil = stmtj.executeQuery(query);
                
                while (hasil.next())
                {
                    //txt berarti dari field ,getstring(ngambil dari database coloumn ) 
                    txtKodeBon.setText(hasil.getString("kodebon"));
                    txtNama.setText(hasil.getString("nama"));
                    txtAlamat.setText(hasil.getString("alamat"));
                    txtTelepon.setText(hasil.getString("telepon"));
                    txtJenis.setSelectedItem(hasil.getString("JenisBarang"));
                    txtHarga.setText(hasil.getString("HargaKiloan"));
                    txtBanyakBarang.setText(hasil.getString("BanyakBarang"));
                    
                    
                }
                
            }catch(SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        search_data();
        }
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtBanyakBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBanyakBarangKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanyakBarangKeyReleased

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        IMessage.setText("");
        String Jenis = (String) this.txtJenis.getSelectedItem();
        String Nama = this.txtNama.getText();
        String Alamat = this.txtAlamat.getText();
        String Telepon = this.txtTelepon.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String Tanggal = dateFormat.format(txtTanggal.getDate());
        String Harga = this.txtHarga.getText();
        String Banyak = this.txtBanyakBarang.getText();
        String Total = this.txtTotalHarga.getText();
        DefaultTableModel model=(DefaultTableModel) tabelSetrika.getModel();
        if(Nama.equals("") ||
                Alamat.equals("") ||
                Telepon.equals("") ||
                Harga.equals("") ||
                Banyak.equals("") ||
                Total.equals("")){
            JOptionPane.showMessageDialog(null,"DATA BELUM LENGKAP!");
        } else {
            model.addRow(new Object[]{txtKodeBon.getText(),txtNama.getText(),txtAlamat.getText(),txtTelepon.getText(),Tanggal,Jenis,txtHarga.getText(),txtTotalHarga.getText(),txtBanyakBarang.getText()});
            
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void txtUangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangKeyReleased
        // TODO add your handling code here:
        int t, j , k;
        t = Integer.parseInt(txtSemuaTotal.getText());
        j = Integer.parseInt(txtUang.getText());
        k = j-t;
        txtKembalian.setText(""+k);
    }//GEN-LAST:event_txtUangKeyReleased

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        int z = 0;
        for(int i = 0; i < tabelSetrika.getRowCount();i++){
            z+=Integer.parseInt(tabelSetrika.getValueAt(i, 7).toString());
        }
        txtSemuaTotal.setText(z+"");
    }//GEN-LAST:event_btnTotalActionPerformed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        // TODO add your handling code here:
        if (txtUang.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "SILAHKAN KLIK TOTAL DAN MASUKKAN UANG PELANGGAN!");
        }else{
        PrinterJob pj = PrinterJob.getPrinterJob();        
        pj.setPrintable(new FormSetrika.BillPrintable(),getPageFormat(pj));
        try {
             pj.print();
          
        }
         catch (PrinterException ex) {
                 ex.printStackTrace();
        }
      }
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void tabelSetrikaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSetrikaMouseClicked
        // TODO add your handling code here:
        int selectedRow = tabelSetrika.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tabelSetrika.getModel();
        txtKodeBon.setText(model.getValueAt(selectedRow, 0).toString());
        txtNama.setText(model.getValueAt(selectedRow, 1).toString());
        txtTelepon.setText(model.getValueAt(selectedRow, 3).toString());
        Date start = null;
        try {
            start = new SimpleDateFormat("yyyy-MM-dd").parse((String)tabelSetrika.getValueAt(selectedRow, 4).toString());
        } catch (ParseException ex) {
            Logger.getLogger(FormSetrika.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTanggal.setDate(start);
        txtAlamat.setText(model.getValueAt(selectedRow, 2).toString());
        txtJenis.setSelectedItem(model.getValueAt(selectedRow, 5).toString());
        txtHarga.setText(model.getValueAt(selectedRow, 6).toString());
        txtTotalHarga.setText(model.getValueAt(selectedRow, 7).toString());
        txtBanyakBarang.setText(model.getValueAt(selectedRow, 8).toString());
        
    }//GEN-LAST:event_tabelSetrikaMouseClicked

    public PageFormat getPageFormat(PrinterJob pj)
{
    
    PageFormat pf = pj.defaultPage();
    Paper paper = pf.getPaper();    

    double middleHeight =8.0;  
    double headerHeight = 2.0;                  
    double footerHeight = 2.0;                  
    double width = convert_CM_To_PPI(8);      //printer know only point per inch.default value is 72ppi
    double height = convert_CM_To_PPI(headerHeight+middleHeight+footerHeight); 
    paper.setSize(width, height);
    paper.setImageableArea(                    
        0,
        10,
        width,            
        height - convert_CM_To_PPI(1)
    );   //define boarder size    after that print area width is about 180 points
            
    pf.setOrientation(PageFormat.PORTRAIT);           //select orientation portrait or landscape but for this time portrait
    pf.setPaper(paper);    

    return pf;
}
    
    protected static double convert_CM_To_PPI(double cm) {            
	        return toPPI(cm * 0.393600787);            
}
 
protected static double toPPI(double inch) {            
	        return inch * 72d;            
}






public class BillPrintable implements Printable {
    
   
    
    
  public int print(Graphics graphics, PageFormat pageFormat,int pageIndex) 
  throws PrinterException 
  {    
      
                
        
      int result = NO_SUCH_PAGE;    
        if (pageIndex == 0) {                    
        
            Graphics2D g2d = (Graphics2D) graphics;                    

            double width = pageFormat.getImageableWidth();                    
           
            g2d.translate((int) pageFormat.getImageableX(),(int) pageFormat.getImageableY()); 

            ////////// code by alqama//////////////

            FontMetrics metrics=g2d.getFontMetrics(new Font("Arial",Font.BOLD,7));
        //    int idLength=metrics.stringWidth("000000");
            //int idLength=metrics.stringWidth("00");
            int idLength=metrics.stringWidth("000");
            int amtLength=metrics.stringWidth("000000");
            int qtyLength=metrics.stringWidth("00000");
            int priceLength=metrics.stringWidth("000000");
            int prodLength=(int)width - idLength - amtLength - qtyLength - priceLength-17;

        //    int idPosition=0;
        //    int productPosition=idPosition + idLength + 2;
        //    int pricePosition=productPosition + prodLength +10;
        //    int qtyPosition=pricePosition + priceLength + 2;
        //    int amtPosition=qtyPosition + qtyLength + 2;
            
            int productPosition = 0;
            int discountPosition= prodLength+5;
            int pricePosition = discountPosition +idLength+10;
            int qtyPosition=pricePosition + priceLength + 4;
            int amtPosition=qtyPosition + qtyLength;
            
            
              
        try{
            /*Draw Header*/
            int y=20;
            int yShift = 10;
            int headerRectHeight=15;
            int headerRectHeighta=40;
            
            ///////////////// Product names Get ///////////
                String  Kodebon = txtKodeBon.getText();
                String Nama = txtNama.getText();
                String Telepon = txtTelepon.getText();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String Tanggal = dateFormat.format(txtTanggal.getDate());
                Object Jenis = txtJenis.getSelectedItem();
            ///////////////// Product names Get ///////////
                
            
            ///////////////// Product price Get ///////////
                int Harga = Integer.valueOf(txtHarga.getText());
                int Banyak = Integer.valueOf(txtBanyakBarang.getText());
                int Total = Integer.valueOf(txtSemuaTotal.getText());
                int Uang = Integer.valueOf(txtUang.getText());
                int Kembalian = Integer.valueOf(txtKembalian.getText());
            ///////////////// Product price Get ///////////
                
             g2d.setFont(new Font("Monospaced",Font.PLAIN,9));
            g2d.drawString("-------------------------------------------",12,y);y+=yShift;
            g2d.drawString("            Laundry Bon Receipt            ",12,y);y+=yShift;
            g2d.drawString("-------------------------------------------",12,y);y+=headerRectHeight;
            g2d.drawString(" KodeBon : "+Kodebon+"              "+Tanggal+" ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------------",10,y);y+=headerRectHeight;
            g2d.drawString(" Nama        : "+Nama+"                    ",10,y);y+=yShift;
            g2d.drawString(" Telepon     : "+Telepon+"                 ",10,y);y+=yShift;
            g2d.drawString(" Jenis       : "+Jenis+"                   ",10,y);y+=yShift;
            g2d.drawString(" Harga       : Rp. "+Harga+"               ",10,y);y+=yShift;
            g2d.drawString(" Banyak      : "+Banyak+"                  ",10,y);y+=yShift;
            g2d.drawString(" Subtotal    : Rp. "+Total+"               ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------------",10,y);y+=yShift;
            g2d.drawString(" Total       : Rp. "+Total+"               ",10,y);y+=yShift;
            g2d.drawString(" Uang        : Rp. "+Uang+"                ",10,y);y+=yShift;
            g2d.drawString(" Kembalian   : Rp. "+Kembalian+"           ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------------",10,y);y+=yShift;
            g2d.drawString("                BJ Laundry                 ",10,y);y+=yShift;
            g2d.drawString("Jl. Baru LUK Kavling Star Motor No.42-43   ",10,y);y+=yShift;
            g2d.drawString("             Tangerang Selatan             ",10,y);y+=yShift;
            g2d.drawString(" Telp. 021-728 79228, Fax. 021-758 79228   ",10,y);y+=yShift;
            g2d.drawString("*******************************************",10,y);y+=yShift;
            g2d.drawString("      Terima Kasih Sudah Mempercayai       ",10,y);y+=yShift;
            g2d.drawString("*******************************************",10,y);y+=yShift;
                   
           
             
           
            
//            g2d.setFont(new Font("Monospaced",Font.BOLD,10));
//            g2d.drawString("Customer Shopping Invoice", 30,y);y+=yShift; 
          

    }
    catch(Exception r){
    r.printStackTrace();
    }

              result = PAGE_EXISTS;    
          }    
          return result;    
      }
  
    private void tabelSetrikaMouseClicked(java.awt.event.MouseEvent evt) {
    int selectedRow = tabelSetrika.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tabelSetrika.getModel();
        txtKodeBon.setText(model.getValueAt(selectedRow, 0).toString());
        txtNama.setText(model.getValueAt(selectedRow, 1).toString());
        txtTelepon.setText(model.getValueAt(selectedRow, 3).toString());
        Date start = null;
        try {
            start = new SimpleDateFormat("yyyy-MM-dd").parse((String)tabelSetrika.getValueAt(selectedRow, 4).toString());
        } catch (ParseException ex) {
            Logger.getLogger(FormSetrika.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTanggal.setDate(start);
        txtAlamat.setText(model.getValueAt(selectedRow, 2).toString());
        txtJenis.setSelectedItem(model.getValueAt(selectedRow, 5).toString());
        txtHarga.setText(model.getValueAt(selectedRow, 6).toString());
        txtTotalHarga.setText(model.getValueAt(selectedRow, 7).toString());
        txtBanyakBarang.setText(model.getValueAt(selectedRow, 8).toString());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSetrika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSetrika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSetrika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSetrika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSetrika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnPrint;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelSetrika;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtBanyakBarang;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JComboBox<String> txtJenis;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtKodeBon;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSemuaTotal;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtUang;
    // End of variables declaration//GEN-END:variables
}
